postgres: &postgres
  adapter:  postgresql
  host:     localhost
  username: boekhouding
  password: boekhouding

development:
  <<: *postgres
  database: boekhouding_development

test:
  <<: *postgres
  database: boekhouding_test

production:
  <<: *postgres
  database: boekhouding_production