development:
  adapter: postgresql
  encoding: unicode
  database: boekhouding_development
  pool: 5
  username: boekhouding
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: boekhouding_test
  pool: 5
  username: boekhouding
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: boekhouding_production
  pool: 5
  username: boekhouding
  password:
